require("plugconfigs._cmp")
require("plugconfigs._lsp")
require("plugconfigs._toggleterm")
require("plugconfigs._telescope")
require("plugconfigs._comment")
require("plugconfigs._catppuccin")
require("plugconfigs._auto-save")
